### ISSUE TITLE
Android not working?

### ISSUE THREAD

**Issue by thomasuster** [haxenme/nme#720]
```bash
cd DisplayingABitmap
haxelib run nme build android -toolkit -gradle
```

Expected: Should build
Result:
```
Error: project/src/audio/OpenSlSound.cpp:405:7: error: use of undeclared identifier 'HxAtomicDec'
      HxAtomicDec(&activeBuffers);
      ^
project/src/audio/OpenSlSound.cpp:411:7: error: use of undeclared identifier 'HxAtomicInc'
      HxAtomicInc(&activeBuffers);
      ^
project/src/audio/OpenSlSound.cpp:675:7: error: use of undeclared identifier 'HxAtomicDec'
      HxAtomicDec(&activeBuffers);
      ^
3 errors generated.

```

Using:
HXCPP: https://github.com/HaxeFoundation/hxcpp/commit/298ad2d6589f9eca4a46e1c2ea7892e124285b74
Haxe: 4.3.2

**Comment by slabgames** [comment]
does it mean, NME doesn't run on Android at the moment?

**Comment by hughsando** [comment]
Looks like hxcpp atomic code has been updated, but the android case has been ignored.
Will need a fix in hxcpp.

**Comment by slabgames** [comment]
Is there a temporary workaround for this? @hughsando

**Comment by Apprentice-Alchemist** [comment]
Use of `HxAtomicInc` needs to be replaced with `_hx_atomic_add`.
and use of `HxAtomicDec` with `_hx_atomic_sub`.

The new atomic functions are declared in `hx/StdLibs.h` (https://github.com/HaxeFoundation/hxcpp/blob/45ee673796438ea5e8e57cb9ee4b7f47ea47d213/include/hx/StdLibs.h#L351).

This was indeed caused by https://github.com/HaxeFoundation/hxcpp/pull/985 and it is not an Android-specific issue, the old atomic functions are gone on all targets.
I suppose I should have known better than to expect hxcpp to be the only consumer of these functions.

**Comment by thomasuster** [comment]
Thanks @Apprentice-Alchemist I can get it building now.

@hughsando Any ideas for how to fix this crash I'm getting on startup?

See stacktrace in https://github.com/haxenme/nme/pull/722 description.

**Comment by hughsando** [comment]
I have put in some android changes I have been sitting on because of lack of proper testing.  But see how they go.

**Comment by hughsando** [comment]
The stack trace is showing "neon" which is not available on the simulator (it is ARM only), so there is something off with the #defines.  In OGLTexture I added ANDROID_SIM, but it might need to be put in a few more places.

**Comment by thomasuster** [comment]
Hmmm, got it building and running on mac using your latest change with one change, but getting the same runtime error with `png_do_expand_palette_rgb8_neon`. Which seems to be some function inside libpng? Took a look at OGLTexture, but not sure how to modify the defines to get it working.
```
diff --git a/templates/android/PROJ-gradle/app/src/main/AndroidManifest.xml b/templates/android/PROJ-gradle/app/src/main/AndroidManifest.xml
index 7a3dc7eb..fbb8989a 100644
--- a/templates/android/PROJ-gradle/app/src/main/AndroidManifest.xml
+++ b/templates/android/PROJ-gradle/app/src/main/AndroidManifest.xml
@@ -17,7 +17,7 @@
    <application
        android:label="::APP_TITLE::"
        ::if (DEBUGGABLE):: android:debuggable="true" ::end::
-       ::if (HAS_ICON):: android:icon="@mipmap/icon"::end::
+       ::if (HAS_ICON):: android:icon="@drawable/icon"::end::
        ::if (HAS_BANNER):: android:banner="@drawable/banner"::end::
        ::foreach appHeader:: ::__current__:: ::end::
    >
```

**Comment by thomasuster** [comment]
@hughsando This seems to fix it. Request for review, https://github.com/native-toolkit/libpng/pull/3
